### ISSUE TITLE
Use Keychain to store user access tokens securely

### ISSUE THREAD

**Issue by KyleErhabor** [KyleErhabor/clematis#4]
At the moment, user tokens are stored in the user's default database. While this is easy, it's not as secure as storing them in Keychain to meet expected requirements. This should be implemented before production reaches.

Documentation: https://developer.apple.com/documentation/security/keychain_services/keychain_items/using_the_keychain_to_manage_user_secrets

**Comment by kyleerhabor** [comment]
Merged as of fa1930f.
